services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    environment:
      - SPARK_ROLE=master
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
    networks:
      - spark-net
    volumes:
      - ./resources:/home/resources
    deploy:
      resources:
        limits:
          cpus: "${MASTER_CPU_LIMIT}"         # CPU limit for the master from .env
          memory: "${MASTER_MEM_LIMIT}"       # Memory limit for the master from .env
        reservations:
          cpus: "${MASTER_CPU_RESERVATION}"   # CPU reservation for the master from .env
          memory: "${MASTER_MEM_RESERVATION}" # Memory reservation for the master from .env

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_ROLE=worker
    depends_on:
      - spark-master
    networks:
      - spark-net
    volumes:
      - ./resources:/home/resources
    deploy:
      replicas: ${WORKER_COUNT}  # Set the number of replicas based on the WORKER_COUNT variable
      resources:
        limits:
          cpus: "${WORKER_CPU_LIMIT}"         # CPU limit for each worker from .env
          memory: "${WORKER_MEM_LIMIT}"       # Memory limit for each worker from .env
        reservations:
          cpus: "${WORKER_CPU_RESERVATION}"   # CPU reservation for each worker from .env
          memory: "${WORKER_MEM_RESERVATION}" # Memory reservation for each worker from .env
  
networks:
  spark-net:
    driver: bridge
